commited

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,6 +11,12 @@ jobs:
   echo-bye:
     runs-on: ubuntu-latest
     steps:
+      - name: failed job
+        run: |
+          echo "its failed job"
+          exit 1
+          
+    
       - name: echo naming bye
         run : echo "byes byes"
       
